package com.distributor.mapper;

import java.util.List;

import com.distributor.model.DistributorCommissionCommodity;

public interface DistributorCommissionCommodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission_commodity
     *
     * @mbggenerated Fri Aug 21 12:25:53 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission_commodity
     *
     * @mbggenerated Fri Aug 21 12:25:53 CST 2015
     */
    int insert(DistributorCommissionCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission_commodity
     *
     * @mbggenerated Fri Aug 21 12:25:53 CST 2015
     */
    int insertSelective(DistributorCommissionCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission_commodity
     *
     * @mbggenerated Fri Aug 21 12:25:53 CST 2015
     */
    DistributorCommissionCommodity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission_commodity
     *
     * @mbggenerated Fri Aug 21 12:25:53 CST 2015
     */
    int updateByPrimaryKeySelective(DistributorCommissionCommodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission_commodity
     *
     * @mbggenerated Fri Aug 21 12:25:53 CST 2015
     */
    int updateByPrimaryKey(DistributorCommissionCommodity record);
    
    List<DistributorCommissionCommodity> getListByDistributorCommissionId(Long distributorCommissionId);
}