package com.distributor.mapper;

import java.util.List;
import java.util.Map;

import com.distributor.model.Distributor;

public interface DistributorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor
     *
     * @mbggenerated Sat Aug 01 23:09:59 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor
     *
     * @mbggenerated Sat Aug 01 23:09:59 CST 2015
     */
    int insert(Distributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor
     *
     * @mbggenerated Sat Aug 01 23:09:59 CST 2015
     */
    int insertSelective(Distributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor
     *
     * @mbggenerated Sat Aug 01 23:09:59 CST 2015
     */
    Distributor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor
     *
     * @mbggenerated Sat Aug 01 23:09:59 CST 2015
     */
    int updateByPrimaryKeySelective(Distributor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor
     *
     * @mbggenerated Sat Aug 01 23:09:59 CST 2015
     */
    int updateByPrimaryKey(Distributor record);
    
    List<Distributor> selectAllDistributors();
    
    int deleteDistributor(Long id);
    
    List<Distributor> selectSelective(Map<String, Object> param);
    
    int getCountAll();
    
}