package com.distributor.mapper;

import java.util.List;
import java.util.Map;

import com.distributor.model.DistributorCommission;

public interface DistributorCommissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    int insert(DistributorCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    int insertSelective(DistributorCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    DistributorCommission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    int updateByPrimaryKeySelective(DistributorCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributor_commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    int updateByPrimaryKey(DistributorCommission record);
    
    DistributorCommission selectLatestRecordById(Long distributorId);
    
    List<DistributorCommission> selectCommissionsSelective(Map<String, Object> param);
    
    int getCountSelective(Map<String, Object> param);
}