package com.distributor.mapper;

import java.util.List;
import java.util.Map;

import com.distributor.model.SystemLog;

public interface SystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int insert(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int insertSelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    SystemLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int updateByPrimaryKeySelective(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_log
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int updateByPrimaryKey(SystemLog record);
    
    List<SystemLog> selectAllLogs(Map<String, Object> param);
    
    int getAllLogsCount();
    
    List<SystemLog> selectLogsByUser(Map<String, Object> param);
    
    int getLogsByUserCount(Map<String, Object> param);
}