package com.distributor.mapper;

import java.util.List;
import java.util.Map;

import com.distributor.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    int updateByPrimaryKey(User record);
    
    User selectUserSelective(Map<String, Object> param);
    
    List<User> selectAllUsers(Map<String, Object> param);
    
    int getCountAll();
    
    List<User> selectRegisterUsers();
    
    void allowRegisterUser(Long id);
    
    void rejectRegisterUser(Long id);
    
    void deleteUser(Long id);
    
    User selectByUserName(String name);
}