package com.distributor.model;

import com.distributor.utils.CommonUtils;

public class Commodity {
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.name
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.price
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.description
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.status
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.category_id
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    private Long categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.price
     *
     * @return the value of commodity.price
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.price
     *
     * @param price the value for commodity.price
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.description
     *
     * @return the value of commodity.description
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.description
     *
     * @param description the value for commodity.description
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.status
     *
     * @return the value of commodity.status
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.status
     *
     * @param status the value for commodity.status
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.category_id
     *
     * @return the value of commodity.category_id
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.category_id
     *
     * @param categoryId the value for commodity.category_id
     *
     * @mbggenerated Mon Aug 03 21:33:08 CST 2015
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    private String brand;
	
    public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}
	
	public String getPriceDisplay() {
		return CommonUtils.priceInt2Float(getPrice());
	}

	public void setPriceDisplay(String priceDisplay) {
		//this.priceDisplay = priceDisplay;
	}
	
	public Integer vipVip;
	
	public Integer vipGold;
	
	public Integer vipDiamond;
	
	public Integer goldGold;
	
	public Integer goldDiamond;
	
	public Integer diamondDiamond;

	public Integer getVipVip() {
		return vipVip;
	}

	public void setVipVip(Integer vipVip) {
		this.vipVip = vipVip;
	}

	public Integer getVipGold() {
		return vipGold;
	}

	public void setVipGold(Integer vipGold) {
		this.vipGold = vipGold;
	}

	public Integer getVipDiamond() {
		return vipDiamond;
	}

	public void setVipDiamond(Integer vipDiamond) {
		this.vipDiamond = vipDiamond;
	}

	public Integer getGoldGold() {
		return goldGold;
	}

	public void setGoldGold(Integer goldGold) {
		this.goldGold = goldGold;
	}

	public Integer getGoldDiamond() {
		return goldDiamond;
	}

	public void setGoldDiamond(Integer goldDiamond) {
		this.goldDiamond = goldDiamond;
	}

	public Integer getDiamondDiamond() {
		return diamondDiamond;
	}

	public void setDiamondDiamond(Integer diamondDiamond) {
		this.diamondDiamond = diamondDiamond;
	}

}