package com.distributor.model;

import com.distributor.utils.CommonUtils;

public class Commodity {
	
	private String categoryName;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.name
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.brand
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.price
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.vip_vip
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Integer vipVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.vip_gold
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Integer vipGold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.vip_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Integer vipDiamond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.gold_gold
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Integer goldGold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.gold_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Integer goldDiamond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.diamond_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Integer diamondDiamond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.description
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.status
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.category_id
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    private Long categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.brand
     *
     * @return the value of commodity.brand
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.brand
     *
     * @param brand the value for commodity.brand
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.price
     *
     * @return the value of commodity.price
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.price
     *
     * @param price the value for commodity.price
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.vip_vip
     *
     * @return the value of commodity.vip_vip
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Integer getVipVip() {
        return vipVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.vip_vip
     *
     * @param vipVip the value for commodity.vip_vip
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setVipVip(Integer vipVip) {
        this.vipVip = vipVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.vip_gold
     *
     * @return the value of commodity.vip_gold
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Integer getVipGold() {
        return vipGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.vip_gold
     *
     * @param vipGold the value for commodity.vip_gold
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setVipGold(Integer vipGold) {
        this.vipGold = vipGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.vip_diamond
     *
     * @return the value of commodity.vip_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Integer getVipDiamond() {
        return vipDiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.vip_diamond
     *
     * @param vipDiamond the value for commodity.vip_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setVipDiamond(Integer vipDiamond) {
        this.vipDiamond = vipDiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.gold_gold
     *
     * @return the value of commodity.gold_gold
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Integer getGoldGold() {
        return goldGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.gold_gold
     *
     * @param goldGold the value for commodity.gold_gold
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setGoldGold(Integer goldGold) {
        this.goldGold = goldGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.gold_diamond
     *
     * @return the value of commodity.gold_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Integer getGoldDiamond() {
        return goldDiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.gold_diamond
     *
     * @param goldDiamond the value for commodity.gold_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setGoldDiamond(Integer goldDiamond) {
        this.goldDiamond = goldDiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.diamond_diamond
     *
     * @return the value of commodity.diamond_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Integer getDiamondDiamond() {
        return diamondDiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.diamond_diamond
     *
     * @param diamondDiamond the value for commodity.diamond_diamond
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setDiamondDiamond(Integer diamondDiamond) {
        this.diamondDiamond = diamondDiamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.description
     *
     * @return the value of commodity.description
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.description
     *
     * @param description the value for commodity.description
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.status
     *
     * @return the value of commodity.status
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.status
     *
     * @param status the value for commodity.status
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.category_id
     *
     * @return the value of commodity.category_id
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.category_id
     *
     * @param categoryId the value for commodity.category_id
     *
     * @mbggenerated Wed Aug 19 21:57:05 CST 2015
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
    
    public Float getDisplayPrice(){
    	return CommonUtils.intPrice2Float(getPrice());
    }
    public void setDisplayPrice(){}
    
    public void setDisplayVipVip(){}
    public Float getDisplayVipVip(){
    	return CommonUtils.intPrice2Float(getVipVip());
    }
    
    public void setDisplayVipGold(){}
    public Float getDisplayVipGold(){
    	return CommonUtils.intPrice2Float(getVipGold());
    }
    
    public void setDisplayVipDiamond(){}
    public Float getDisplayVipDiamond(){
    	return CommonUtils.intPrice2Float(getVipDiamond());
    }
    
    public void setDisplayGoldGold(){}
    public Float getDisplayGoldGold(){
    	return CommonUtils.intPrice2Float(getGoldGold());
    }
    
    public void setDisplayGoldDiamond(){}
    public Float getDisplayGoldDiamond(){
    	return CommonUtils.intPrice2Float(getGoldDiamond());
    }
    
    public void setDisplayDiamondDiamond(){}
    public Float getDisplayDiamondDiamond(){
    	return CommonUtils.intPrice2Float(getDiamondDiamond());
    }
    
	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}
    
}