package com.distributor.model;

import java.util.Date;

public class DistributorBalance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_balance.id
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_balance.distributor_id
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    private Long distributorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_balance.balance_change
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    private Integer balanceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_balance.balance
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_balance.create_time
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_balance.id
     *
     * @return the value of distributor_balance.id
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_balance.id
     *
     * @param id the value for distributor_balance.id
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_balance.distributor_id
     *
     * @return the value of distributor_balance.distributor_id
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public Long getDistributorId() {
        return distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_balance.distributor_id
     *
     * @param distributorId the value for distributor_balance.distributor_id
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public void setDistributorId(Long distributorId) {
        this.distributorId = distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_balance.balance_change
     *
     * @return the value of distributor_balance.balance_change
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public Integer getBalanceChange() {
        return balanceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_balance.balance_change
     *
     * @param balanceChange the value for distributor_balance.balance_change
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public void setBalanceChange(Integer balanceChange) {
        this.balanceChange = balanceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_balance.balance
     *
     * @return the value of distributor_balance.balance
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_balance.balance
     *
     * @param balance the value for distributor_balance.balance
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_balance.create_time
     *
     * @return the value of distributor_balance.create_time
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_balance.create_time
     *
     * @param createTime the value for distributor_balance.create_time
     *
     * @mbggenerated Tue Aug 18 16:35:42 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}