package com.distributor.model;

public class DistributorInclude {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_include.id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_include.parent_id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_include.child_id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    private Long childId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_include.id
     *
     * @return the value of distributor_include.id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_include.id
     *
     * @param id the value for distributor_include.id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_include.parent_id
     *
     * @return the value of distributor_include.parent_id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_include.parent_id
     *
     * @param parentId the value for distributor_include.parent_id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_include.child_id
     *
     * @return the value of distributor_include.child_id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    public Long getChildId() {
        return childId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_include.child_id
     *
     * @param childId the value for distributor_include.child_id
     *
     * @mbggenerated Sun Aug 02 11:27:33 CST 2015
     */
    public void setChildId(Long childId) {
        this.childId = childId;
    }
}