package com.distributor.model;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.distributor.utils.CommonUtils;

public class DistributorCommission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_commission.id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_commission.distributor_id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    private Long distributorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_commission.order_id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_commission.percent
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    private Integer percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_commission.commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    private Integer commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_commission.totalCommission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    private Integer totalcommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_commission.create_time
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributor_commission.status
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_commission.id
     *
     * @return the value of distributor_commission.id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_commission.id
     *
     * @param id the value for distributor_commission.id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_commission.distributor_id
     *
     * @return the value of distributor_commission.distributor_id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public Long getDistributorId() {
        return distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_commission.distributor_id
     *
     * @param distributorId the value for distributor_commission.distributor_id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public void setDistributorId(Long distributorId) {
        this.distributorId = distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_commission.order_id
     *
     * @return the value of distributor_commission.order_id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_commission.order_id
     *
     * @param orderId the value for distributor_commission.order_id
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_commission.percent
     *
     * @return the value of distributor_commission.percent
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public Integer getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_commission.percent
     *
     * @param percent the value for distributor_commission.percent
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_commission.commission
     *
     * @return the value of distributor_commission.commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public Integer getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_commission.commission
     *
     * @param commission the value for distributor_commission.commission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public void setCommission(Integer commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_commission.totalCommission
     *
     * @return the value of distributor_commission.totalCommission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public Integer getTotalcommission() {
        return totalcommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_commission.totalCommission
     *
     * @param totalcommission the value for distributor_commission.totalCommission
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public void setTotalcommission(Integer totalcommission) {
        this.totalcommission = totalcommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_commission.create_time
     *
     * @return the value of distributor_commission.create_time
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_commission.create_time
     *
     * @param createTime the value for distributor_commission.create_time
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributor_commission.status
     *
     * @return the value of distributor_commission.status
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributor_commission.status
     *
     * @param status the value for distributor_commission.status
     *
     * @mbggenerated Wed Aug 12 22:51:50 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    
	public float getDisplayTotalCommission() {
		return CommonUtils.intPrice2Float(getTotalcommission());
	}

	public void setDisplayMoney(float displayMoney) {
	}

	public float getDisplayCommission() {
		return CommonUtils.intPrice2Float(getCommission());
	}

	public void setDisplayCommission(float displayCommission) {
	}

	public String getDisplayCreateTime() {
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return format.format(getCreateTime());
	}

	public void setDisplayCreateTime(String displayCreateTime) {
	}


}