package com.distributor.model;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.distributor.utils.CommonUtils;

public class OrderRecord {
	
	private Distributor orderDistributor;
	
	private Distributor bossDistributor;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.id
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.distributor_id
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    private Long distributorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.money
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.commission
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    private Integer commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.create_time
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.id
     *
     * @return the value of order_record.id
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.id
     *
     * @param id the value for order_record.id
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.distributor_id
     *
     * @return the value of order_record.distributor_id
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public Long getDistributorId() {
        return distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.distributor_id
     *
     * @param distributorId the value for order_record.distributor_id
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public void setDistributorId(Long distributorId) {
        this.distributorId = distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.money
     *
     * @return the value of order_record.money
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.money
     *
     * @param money the value for order_record.money
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.commission
     *
     * @return the value of order_record.commission
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public Integer getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.commission
     *
     * @param commission the value for order_record.commission
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public void setCommission(Integer commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.create_time
     *
     * @return the value of order_record.create_time
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.create_time
     *
     * @param createTime the value for order_record.create_time
     *
     * @mbggenerated Wed Aug 12 00:13:58 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /*public float getDisplayMoney() {
		return CommonUtils.intPrice2Float(getMoney());
	}

	public void setDisplayMoney(float displayMoney) {
		
	}

	public float getDisplayCommission() {
		return CommonUtils.intPrice2Float(getCommission());
	}

	public void setDisplayCommission(float displayCommission) {
		
	}

	public String getDisplayCreateTime() {
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return format.format(getCreateTime());
	}

	public void setDisplayCreateTime(String displayCreateTime) {
		
	}*/

	public Distributor getOrderDistributor() {
		return orderDistributor;
	}

	public void setOrderDistributor(Distributor orderDistributor) {
		this.orderDistributor = orderDistributor;
	}

	public Distributor getBossDistributor() {
		return bossDistributor;
	}

	public void setBossDistributor(Distributor bossDistributor) {
		this.bossDistributor = bossDistributor;
	}
}