package com.distributor.model;

public class OrderCommodityInclude {
	private Commodity commodity;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_include.id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_include.order_id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_include.commodity_id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    private Long commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_include.commodity_count
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    private Integer commodityCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity_include.status
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_include.id
     *
     * @return the value of order_commodity_include.id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_include.id
     *
     * @param id the value for order_commodity_include.id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_include.order_id
     *
     * @return the value of order_commodity_include.order_id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_include.order_id
     *
     * @param orderId the value for order_commodity_include.order_id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_include.commodity_id
     *
     * @return the value of order_commodity_include.commodity_id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public Long getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_include.commodity_id
     *
     * @param commodityId the value for order_commodity_include.commodity_id
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public void setCommodityId(Long commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_include.commodity_count
     *
     * @return the value of order_commodity_include.commodity_count
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public Integer getCommodityCount() {
        return commodityCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_include.commodity_count
     *
     * @param commodityCount the value for order_commodity_include.commodity_count
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public void setCommodityCount(Integer commodityCount) {
        this.commodityCount = commodityCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity_include.status
     *
     * @return the value of order_commodity_include.status
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity_include.status
     *
     * @param status the value for order_commodity_include.status
     *
     * @mbggenerated Sun Aug 09 22:04:56 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Commodity getCommodity() {
		return commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}
    
}