package com.distributor.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.distributor_id
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    private Long distributorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.commission
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    private Integer commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.distributor_id
     *
     * @return the value of order.distributor_id
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public Long getDistributorId() {
        return distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.distributor_id
     *
     * @param distributorId the value for order.distributor_id
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public void setDistributorId(Long distributorId) {
        this.distributorId = distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money
     *
     * @return the value of order.money
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money
     *
     * @param money the value for order.money
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.commission
     *
     * @return the value of order.commission
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public Integer getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.commission
     *
     * @param commission the value for order.commission
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public void setCommission(Integer commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated Sun Aug 09 21:41:56 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}