package com.distributor.model;

import java.text.SimpleDateFormat;
import java.util.Date;

public class SystemLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.id
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.content
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.use_id
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    private Long useId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_log.create_time
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.id
     *
     * @return the value of system_log.id
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.id
     *
     * @param id the value for system_log.id
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.content
     *
     * @return the value of system_log.content
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.content
     *
     * @param content the value for system_log.content
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.use_id
     *
     * @return the value of system_log.use_id
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    public Long getUseId() {
        return useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.use_id
     *
     * @param useId the value for system_log.use_id
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    public void setUseId(Long useId) {
        this.useId = useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_log.create_time
     *
     * @return the value of system_log.create_time
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_log.create_time
     *
     * @param createTime the value for system_log.create_time
     *
     * @mbggenerated Sat Aug 08 21:48:10 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    public String getDisplayCreateTime() {
    	SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		return format.format(getCreateTime());
    }

    public void setDisplayCreateTime() {
    }
}